### ISSUE TITLE
IE11 storage event behavior blocks IWC traffic

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#301]
Testing against my IE11 VM, the election operation does not settle, it seems 2 applications open (debugger & iframe_peer or bouncing balls) will keep fighting for coordinator status, or not communicate at all.

**IE storage event differences from the w3c  standards:**
* 10: The writer to localstorage receives the storage event.
    * Not an issue for IWC as filtering on self sent/duplicates is taken care of.
* 11: If the iframe is embedded in a page that is different from that which triggered the storage event, the event will not fire at all within that iframe.
    * Prevents sending/receiving IWC messages 
* 11: If the event is triggered from an iframe, it will fire locally and  in any other iframe embedded in the same page, but not at all in iframes of other pages.
    * Prevents sending/receiving IWC messages

**Comment by Kevin-K** [comment]
![tmp](https://cloud.githubusercontent.com/assets/7290455/9014094/25a65d8e-378e-11e5-80da-2b25671026ae.png)

Replicating:
1) Open a debugger with no IWC instances open (now the leader)
2) go to elections tab and enable.
2) Open a 2nd debugger, go to systemAPI and launch a application listing
3) close opened application.

When the bouncing balls (or other application) is opened, it does not receive messages from the other participants on the bus (debuggers) but its messages do make it outbound. We know this because both debuggers will retry election (since they have a higher priority because they were opened before the application) but bouncing balls does not yeild as it should (because it is not receiving messages).

**Comment by Kevin-K** [comment]
Took a step back and tested localstorage on ie11 (11.0.9600.16428):
**test.html**
```
<!DOCTYPE html>
<head>
    <title>TEST</title>

    <script type="text/javascript">
        var createIframeShim=function() {
            var iframe = document.createElement("iframe");
            iframe.addEventListener("load",function() {
                console.log("Loaded Iframe.");
            });
            var url="iframe.html";
            iframe.src=url;
            iframe.height=1;
            iframe.width=1;
            iframe.setAttribute("area-hidden",true);
            iframe.setAttribute("hidden",true);
            iframe.style.setProperty ("display", "none", "important");
            document.body.appendChild(iframe);
            console.log(iframe.contentWindow);
        };

        createIframeShim();
    </script>
  </head>
  <body>
  </body>
</html>
```

**iframe.html**
```
<script type="text/javascript">
    var id = Date.now();
    window.addEventListener('storage', function(evt){
        console.log(id, evt.newValue);
    });
    window.setInterval(function(){
        localStorage.setItem("x",Date.now());
    },1000);
</script>
```
Hosted these two files from the same domain and same directory.


**Expected behavior**: Open 2 instances of test.html, open the debugger, and each instance will print out messages from the other. **This is the case in Chrome (and assuming FF)**

**IE Behavior**: Open 2 instances of test.html, open the debugger, and each instance will print out messages **from itself** and **not print out message from the other window**.  IE 11 will print duplicated messages as well, the IWC handles these already.

I feel we already validated functionality working in IE11, but I'm wondering if we tested 2 widgets open in a gridster versus 2 separate browser windows (which in terms of localstorage should not matter).

**Comment by Kevin-K** [comment]
Msdn issue: https://connect.microsoft.com/IE/feedback/details/811546/ie11-localstorage-events-fire-twice-or-not-at-all-in-iframes

Demonstration of issue (chrome working on top, IE11 on bottom): http://gifx.co/z4fn

**Comment by Kevin-K** [comment]
Since this ie11 storage event behavior limits IWC communication to iwc widgets in the same tab, currently bouncing balls will only work if opened in same window (webtop/gridster) & intents will not work if the chooser is opened (different window).

A fix for the intent chooser: have the chooser register event listeners to its `window.parent` as it is opened by the bus and domain matching can be ensured. This is not a fix for widget use though, as the client iframe can be opened from any domain.

**Comment by Kevin-K** [comment]
Registering the opened intent chooser's events off of `window.opener` allows retrieval of events as they would be received by its opener, but the problem lies in the opener and not the intent chooser (intent chooser doesn't use iFrames but its opener does). The opener of the intent chooser has the missing storage event issue, thus tieing to its events does not help.

Current course of action is to label IWC for IE11 to be bound to single window use (everything contained in webtop). Collaboration will be needed with webtop to    devise a intent chooser modal integration (wrapping the intent chooser in a modal/iFrame should suffice).

@arw180 @hoganmaps @SOAP1914 : I'm going to put something functional together and open an issue on webtop to continue this effort. There are 2 paths I see we could take:


1) Override IWC's `openWindow` in webtop if IE11 to open a modal.
      + low overhead for development. Simply include the IWC and override the method.
      - puts a dependency on webtop for IWC.
      - puts browser detection code on webtop (IWC already uses it so spreading it  I'm considering a con)

2) Implement an event based `openWindow` on the IWC. Allows registration to handle the window launching without an IWC dependency. If no handler is registered, the IWC will default to using the default behavior (open in a popup).
    + modular
    + Non-intrusive, no overriding functionality, if something fails in the registration of the handler default behavior can be a fallback.
    - Webtop will still have to do browser detection to know to register to handle the custom functionality if IE11. (Con on both approaches)

Moving forward on approach 2, approach 1 can be held onto as a fallback option should timeframe needs arrise.

**Comment by Kevin-K** [comment]
Approach 2 will only work if same domain. Registering event handlers on the document which the IWC is running from isn't possible if CORS permissions are not in place. 

New approach:
Webtop has its own IWC client that will register to handle the window opening intent. 

**Pros:**
+ No overriding
+ Gain benefit of webtop awareness (for Chrome/FF). when IWC launches a widget, the user can select which open webtop (if more than 1) to launch into.
+ Better IWC performance. Webtop instances have longer lifespans than widgets.   With the DOM creation timeline, the webtop will create its IWC instance before its widgets, thus treating it as the leader. This gives the following benefits:
    * Less IWC consensus runs -> higher performance
    * Ephemeral data lifespan will be lifespan of the webtop, if all applications open are closed the ephemeral data will still be retained until the webtop (and all other IWC instances) is closed.

**Cons:**
* IWC dependency. This is a minimal dependency, all IWC functionality can be contained in an angular service, if the IWC connection fails the webtop should continue normal functionality.

**Comment by cgross** [comment]
Have you guys tested this lately?  I just noticed this SO question and they said it was fixed in IE11 sometime in October:

http://stackoverflow.com/questions/20565508/how-to-work-around-ie11-localstorage-events-firing-twice-or-not-at-all-in-iframe

Not sure why the issue at the MS Connect website wasn't updated.  Would be nice to hear from you guys that its working.

**Comment by Kevin-K** [comment]
That's the first I've heard about this! I'm shocked that it got fixed. 

Reopening and will pull down an updated IE 11 vm to test this out. 

There was some major fixes for the overhead of the communication so this may bring some hope for better support of older IE versions, IE 10 wasn't keeping up with the timing requirements of IWC before.

**Comment by cgross** [comment]
Good to hear.  If those changes and this fix are all working then it would be great to be able to say IE 10+ works without caveat.  Some of our users, unfortunately, are still stuck on IE.

**Comment by Kevin-K** [comment]
With my current development setup I'm having trouble trying to test against a version equal to or later than the IE 11 build linked in that Stack Overflow post. Pulling down the latest IE 11 vm from modern.ie gives a build previous to the October one listed. 

Any input on how to get a vm  of IE v11.0.9600.16476 or later would be appreciated.

**Comment by cgross** [comment]
Are you trying the Win7 or Win8 vms?  It looks like the Win8 version of IE is older.  The Win7 vm seems to have a later version of IE than 11.0.9600.16476.   That said, it didnt look like the problem was fixed when I played around with the test site linked in that SO thread.

**Comment by Kevin-K** [comment]
Strange I must have misread the IE version on my vm, I have 11.0.9600.17420.

**Comment by Kevin-K** [comment]
Ah, missed [this comment](http://stackoverflow.com/questions/20565508/how-to-work-around-ie11-localstorage-events-firing-twice-or-not-at-all-in-iframe#comment55381138_20565508) seems the needed functionality wasn't fixed, the comment states "now local storage events not firing between same domain iframes" but that has actually been an issue throughout IE 11 I believe (at least as long as this issue has been open)

**Comment by Kevin-K** [comment]
Moving this issue back to closed, the hotfix for IE 11 didn't fix the issue at hand for IWC. Moving forward, short term goal would be to find a new communication link for IE browsers to utilize (activex/flash/ect). Findings on that will be noted in #199.
